### Add Student
POST http://127.0.0.1:5000/add-student
Content-Type: application/json

{
    "name": "Amol",
    "email": "Amol@example.com",
    "department": "Computer Science"
}

POST http://127.0.0.1:5000/auth/register
Content-Type: application/json

{
    "name": "Mahesh",
    "email": "mahesh@test.com",
    "password": "123456",
    "role_id": 1
}

### Get Students
GET http://127.0.0.1:5000/students
Content-Type: application/json

### Update Student
PUT http://127.0.0.1:5000/update-student/1
Content-Type: application/json

{
    "name": "Mahesh Updated",
    "email": "mahesh_new@example.com",
    "department": "Artificial Intelligence"
}

### Delete Student
DELETE http://127.0.0.1:5000/delete-student/3
Content-Type: application/json